### ISSUE TITLE
ChDM: consumer/producer schemas

### ISSUE THREAD

**Issue by fbalaban** [Agri-Hub/eoProcessors#133]
For the ChDM and respective STAC service

**Comment by fbalaban** [comment]
```
ChDM:
  consumer:
    orderId: str
    initialSelectionProductPaths: [str]
    finalSelectionProductPaths: [str]
    bbox: [double]
  producer:
    result (αυτό σκέψου αν το θέλουμε - 0 για success ένα είδους result status - 1 για failure - 2 για άλλου είδους failure (reserved)
    orderId: str
    chdmProductPath: str
STAC(ChDM):
  consumer:
    orderId: str
    noaId: str
    noaS3Path: str
 producer:
    orderId: str
    result (ίδιο με πάνω - η αλήθεια είναι πως είχαμε μιλήσει για λίστες εδώ - succeeded, failed, αλλά δεν έχει νόημα για αυτό το προιόν. Πάντα ένα θα δημιουργεί/γυρνάει και ένα δημιουργείται από ένα order)
```
